@echo off
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing/Updating dependencies...
pip install -r requirements.txt
echo Running OCR...
python src/ocr_cpu.py %*
pause
